=== ramarble/JS_DOM/trimestre3/html/040203.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="geografiamundial">
    <xsd:complexType>
    <xsd:sequence>
    <xsd:element ref="pais" minOccurs="1" maxOccurs="unbounded">
    </xsd:element>
</xsd:sequence>    
</xsd:complexType>
</xsd:element>
<xsd:element name="pais">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="continente" type="xsd:string"></xsd:element>
            <xsd:element name="capital" type="xsd:string"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="nombre" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
</xsd:element>
</xsd:schema>

=== ramarble/JS_DOM/trimestre3/html/040203.xml
<?xml version="1.0" encoding="UTF-8"?> 
<geografiamundial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="040203.xsd"> 
 <pais nombre="EspaÃ±a"> 
 <continente>Europa</continente> 
 <capital>Madrid</capital> 
 </pais> 
 <pais nombre="Portugal"> 
 <continente>Europa</continente> 
 <capital>Lisboa</capital> 
 </pais> 
 <pais nombre="Argentina"> 
<continente>America del Sur</continente> 
<capital>Buenos Aires</capital> 
</pais> 
<pais nombre="Marruecos"> 
<continente>Africa</continente> 
<capital>Rabat</capital> 
</pais> 
<pais nombre="Jordania"> 
<continente>Asia</continente> 
<capital>Amman</capital> 
</pais> 
</geografiamundial>
